### PR TITLE
Renamed refreshToken() and requestToken() to more descriptive names

### PR DESCRIPTION
**Pull request by hvt**
Renamed refreshToken() and requestToken() to more descriptive names
- Session::refreshToken() -> Session::refreshAccessToken()
- Session::requestToken() -> Session::requestRefreshAndAccessToken()
- Besides, added E_USER_DEPRECATED errors to both old methods

Updated the demo + docs accordingly
Fixed some CS

### CODE REVIEW

**Comment by hvt** [comment]
Yes, I'd like to. Any deadline on that?

**Comment by jwilsson** [comment]
Not really, as soon as possible would be great. So we can tag a 0.8 release.

**Comment by jwilsson** [comment]
@hvt Just wanted to check with you if you wanted to update the docs? I can do it otherwise, I think it's time for a 0.8 release :smile:

**Comment by hvt** [comment]
@jwilsson I'm quite busy right now, so if you'd like :]

**Comment by jwilsson** [comment]
Merged. Thanks for your work!

**Pull request merged**
