### PR TITLE
Added followPlaylist and unfollowPlaylist

### PR DESCRIPTION
**Pull request by vdesabou**
https://github.com/jwilsson/spotify-web-api-php/issues/21

### CODE REVIEW

**Comment by jwilsson** [comment]
I think we should pass `public` as an array instead and make it optional to keep it consistent with other methods (and just in case Spotify decides to add more options we can just extend the array), i.e.

```
$options = array(
    'public' => true
);

$api->followPlaylist('USER_ID', 'PLAYLIST_ID', $options);
```

`updateUserPlaylist()` is a great example of what I'm thinking of.

**Comment by vdesabou** [comment]
See latest change. Let me know if this is ok

**Comment by jwilsson** [comment]
Perhaps I was unclear, sorry about that. 

I meant that the `$options` parameter should be optional as well.

**Comment by vdesabou** [comment]
>I meant that the $options parameter should be optional as well.

I got confused because data is not optional in updateUserPlaylist($userId, $playlistId, $data)

**Comment by jwilsson** [comment]
Then it's definitely my fault, sorry mate!

I'll just run some tests tonight but everything looks good so far.

**Pull request merged**
