### PR TITLE
support php5.6 too

### PR DESCRIPTION
**Pull request by albertborsos**
First, thanks for this awesome package.

I have to use it on a server which runs php 5.6, but this package is not support it.
I checked the source and there is no serious reason to restrict minimum php version to 7.0 :)

With wider requirements your package can reach more people :)

### CODE REVIEW

**Comment by shivampaw** [comment]
With PHP 5 at the end of it's life I wouldn't say supporting it is a "good" thing to do, personally.

**Comment by albertborsos** [comment]
I can agree with you @shivampaw.

I had to modify this package, to use in my app. I can use my fork in production, this PR is just an option. I will not be sad if it will not be merged :)

**Comment by vdesabou** [comment]
I'm using this library to build a Spotify Alfred [workflow](http://alfred-spotify-mini-player.com/) that runs on macOs. If I'm correct, even with macOS Sierra, you get PHP 5.6 installed (High Sierra is using 7.1 now), so currently I have to use a locally modified (basically this PR) version of the library.

A lot of users are still using Mountain Lion for example and most of them are using builtin PHP installation.

My 2 cents

**Comment by andersborgabiro** [comment]
I set the code verification to PHP 5.6 in NetBeans to see what errors popped up.

The only thing I saw was a number of "??" that need to be replaced (might be enough to replace it with isset())

Supposedly "[]" was supported in 5.6, so that shouldn't be an issue.

Not saying this is all, but worth a try.

**Comment by andersborgabiro** [comment]
vdesabou is explaining why.

**Comment by shivampaw** [comment]
So why not upgrade the PHP version?

**Comment by andersborgabiro** [comment]
That affects all users that currently have 5.6.

**Comment by albertborsos** [comment]
I cannot upgrade because the hosting of the project will be on the customer's server which runs 5.6.
This server already hosts several sites.

**Comment by andersborgabiro** [comment]
You might consider Linux-based cloud hosting that generally is at PHP7 now. My hosting is at 7.2.

**Comment by vdesabou** [comment]
@shivampaw 

> So why not upgrade the PHP version?

In my case, users are downloading and installing the workflow on their Mac. Most of them are non tech people and It's difficult to ask them to upgrade the PHP version on their Mac.

**Comment by jwilsson** [comment]
Hi everyone!
While I generally agree with @shivampaw given that `5.6` is end-of-life, I didn't know a lot of people are still on 5.6. 

The changes in this PR should be enough to support it, but let me think a little for a little bit on how to approach this, thanks!

**Comment by andersborgabiro** [comment]
Supposedly, the vast majority are still on 5.6: https://w3techs.com/technologies/details/pl-php/all/all
I don't see when these stats were updated though, and I'm not saying this applies to users of this library, that obviously are developers.

Yet, considering supporting 5.6 (and possibly lower) too is trivial, there's nothing really hindering you from being backwards-compatible, but it's up to you.

**Comment by shivampaw** [comment]
https://seld.be/notes/php-versions-stats-2018-1-edition

**Comment by jwilsson** [comment]
Released in `2.3.0`.

Thanks for bringing it to my attention and for doing the changes needed! 🎉

**Pull request closed without merging**
